resources:
  repositories:
  - repository: CICD-Templates
    type: git
    name: tvsmsoftwarefactory/CICD-Templates

trigger:
  - main

pool: 
   name: UFTONE
   demands:
    - agent.name -equals AutoTestingVM

parameters:
  - name: buildtype
    displayName: "Application build type (default is release)"
    type: string
    default: debug


#name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)
variables:
- template: Templates/Variable-Templates/app-var-template-JS.yml@CICD-Templates

stages:
  
  #- template: Templates/Build-Templates/ADO-BuildVersioning.yml@CICD-Templates   # stage for Build versioning
    # parameters:
    #   engagement_name: 'Talisman'
    #   scan_type: 'Talisman Scan' 

  - template: Templates/Scan-Templates/Talisman.yml@CICD-Templates   # stage template reference
    parameters:
      engagement_name: 'Talisman'
      scan_type: 'Talisman Scan'  

  - template: Templates/Scan-Templates/DefectDojo.yml@CICD-Templates   # stage template reference
    parameters:
      engagement_name: 'Talisman'
      scan_type: 'Talisman Scan'   

  - template: Templates/Scan-Templates/Sbom.yml@CICD-Templates  # stage template reference
    parameters:
      engagement_name: 'SBOM'
      scan_type: 'CycloneDX Scan'

  - template: Templates/Scan-Templates/DefectDojo.yml@CICD-Templates   # stage template reference
    parameters:
      engagement_name: 'SBOM'
      scan_type: 'CycloneDX Scan'         


  - template: Templates/Scan-Templates/Python_Snyk_Scan.yml@CICD-Templates   # stage template reference
    parameters:
      engagement_name: 'Snyk'
      scan_type: 'Snyk Scan'

  - template: Templates/Scan-Templates/DefectDojo.yml@CICD-Templates   # stage template reference
    parameters:
      engagement_name: 'Snyk'
      scan_type: 'Snyk Scan'  


  - template: Templates/Scan-Templates/Safety_Scan.yml@CICD-Templates   # stage template reference
    parameters:
      engagement_name: 'Safety_Scan'
      scan_type: 'Safety Scan' 

 
  - template: Templates/Build-Templates/Python_Build_Test.yml@CICD-Templates   # stage template reference

  - template: Templates/Deployment-Templates/Deployment.yml@CICD-Templates  # stage template reference
    parameters:
      env: 'dev'
      condition: succeeded()
      dependsOn: build     
