



trigger: 
- master 
pool: 

  name: UFTONE 

  strategy: 

  matrix: 

    Python27: 

      python.version: '3.6' 

 

steps: 

- task: UsePythonVersion@0 

  inputs: 

    versionSpec: '3.x' 

    addToPath: true 

- task: CmdLine@2 

  displayName: 'Install Safety' 

  inputs: 

    script: 'pip install safety' 

 

- task: CmdLine@2 

  displayName: 'Run Safety Check' 

  inputs: 

    script: 'safety check -r Application/requirements.txt> report.json' 

  continueOnError: true 

- task: PublishBuildArtifacts@1 

  displayName: 'Publish Safety Report' 

  inputs: 

    PathtoPublish: '$(Build.SourcesDirectory)' 

    ArtifactName: 'safety-report' 

    publishLocation: 'Container' 

# - script: |
#              SEVERITY=$(cat $(Build.SourcesDirectory)/report.json | jq -r '.highest_vulnerability.severity')

#              if [[ "$SEVERITY" == "high" ]]; then
#                echo "High severity vulnerability found. Failing the pipeline."
#                exit 1
#              else
#                echo "No high severity vulnerabilities found."
#              fi
#   displayName: 'Check Safety Severity and Fail Pipeline'