trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    npm install -g snyk
  displayName: 'Install Snyk CLI'

- script: |
    snyk auth $SNYK_TOKEN
  displayName: 'Authenticate Snyk'

- script: |
    # Navigate to the Django project directory
    cd path/to/your/django/project

    # Install project dependencies
    pip install -r requirements.txt

    # Run Snyk scan
    snyk test --file=requirements.txt --fail-on=upgradable
  displayName: 'Run Snyk Scan'