parameters:
   - name: env
     type: string
   - name: condition
     type: string
   - name: dependsOn
     type: string
stages:
  - stage: ${{ parameters.env }}
    condition: ${{ parameters.condition }}
    dependsOn: ${{ parameters.dependsOn }}
    jobs:
      # - job: deploy_application
      - deployment: deploy_application
        displayName: Deployt the Application
        pool: '$(windows_pool)'
        environment: ${{ parameters.env }}
        # steps:
        #   - template: Deploy-Apps-template.yml # step template reference


      - job: smoke_test
        displayName: Run Smoke Test
        pool: '$(windows_pool)'
        dependsOn: deploy_application
        condition: in(dependencies.deploy_application.result, 'Succeeded')
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                write-host "Setup running the Smoke Test"
   
   
   
# stages:
#   - stage: deploy
#     jobs:
#     - deployment: deploy_application
#       displayName: Deploy the Application
#       pool: Azure Pipelines
#       environment: 'dev'
#       strategy:
#         runOnce:
#           deploy:
#             steps:
#             - script: echo hello world

