trigger: none

parameters:
  - name: buildtype
    displayName: "Application build type (default is release)"
    type: string
    default: debug

variables:
- template: app-var-template.yml
  #######################
  ##  GLOBAL VARIABLES ##
  #######################
  # onMainBranch: ${{ eq(variables['Build.SourceBranchName'], 'main') }}
  # System.Debug: 'true'
  # NETVersion: '4.8.1'
  # Linux_pool: 'Default'
  # Windows_pool: 'Default'
  # mac_pool: 'Default'
  ########################
  ##   APP & AGENT VARIABLES    ##
  ########################
  # Variable Template reference

stages:

  # - template: Talisman_DefectDojo.yml # stage template reference
  #   parameters:
  #     Buildtype: $(buildtype)  

  # - template: Build_Test.yml # stage template reference
  #   parameters:
  #     Buildtype: $(buildtype)

  # - template: Sbom_DefectDojo.yml # stage template reference
  #   parameters:
  #     Buildtype: $(buildtype)      

  - template: Snyk_DefectDojo.yml # stage template reference
    parameters:
      Buildtype: $(buildtype)       
   

  # - template: Deploy.yml # stage template reference
  #   parameters:
  #     env: 'dev'
  #     condition: succeeded()
  #     dependsOn: build

  # - template: Deploy.yml # stage template reference
  #   parameters:
  #     env: 'test'
  #     condition: succeeded() #and(eq(variables['onMainBranch'], 'true'), succeeded())
  #     dependsOn: dev
      
  # - template: Deploy.yml # stage template reference
  #   parameters:
  #     env: 'prod'
  #     condition: succeeded() #and(eq(variables['onMainBranch'], 'true'), succeeded())
  #     dependsOn: test        



