name: Django-workflow 
on:
  workflow_dispatch: 
  push:
    branches:
      - main
      

env: 
  REPO_NAME: ${{ github.repository }}

permissions: 
    checks: write
    security-events: write
    packages: write
    actions: write
    pull-requests: write
    
jobs:

    Talisman:
      name: Talisman
      uses: ./.github/workflows/talisman.yaml
      secrets: inherit

    Snyk:
      name: Snyk_security_check
      uses: ./.github/workflows/snyk.yaml
      secrets: inherit

    Sbom:
      name: Sbom
      uses: ./.github/workflows/sbom.yaml
      secrets: inherit

    KICS:
      name: KICS Scan
      uses: ./.github/workflows/kics.yaml
      secrets: inherit 

    TicTaac:
      name: TicTaac
      uses: ./.github/workflows/tictaac.yaml
      secrets: inherit 
    
    #Conftest:
    #  name: conftest
    #  uses: ./.github/workflows/conftest.yaml
    #  secrets: inherit

    #Build: 
    #  needs: [Talisman,Snyk,Sbom,KICS,Conftest]
    #  name: Build
    #  uses: ./.github/workflows/Build.yaml
    #  secrets: inherit

    # Unit_Test:
    #   name: Unit Test
    #   uses: ./.github/workflows/UnitTest_reactJs.yaml
    #   secrets: inherit

    #Docker_build:
    #  needs: [Build]
    #  name: Docker build 
    #  uses: ./.github/workflows/docker-build.yaml
    #  secrets: inherit

    #clair_scan:
    #  needs: Docker_build
    #  name: clair
    #  uses: ./.github/workflows/clair_scan.yaml
    #  secrets: inherit

    #Trivy:
    #  needs: [Docker_build]
    #  name: Trivy Scan
    #  uses: ./.github/workflows/trivy_Scan.yaml
    # secrets: inherit
    
    #Deployment:
    #  needs: [Docker_build, Trivy]
    #  name: Deployment
    #  uses: ./.github/workflows/deployment.yaml
    #  secrets: inherit
      
    







  
     